#!/usr/bin/env python
"""
Copyright 2014 Wordnik, Inc.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""
class AggregatesEnvelope:
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        self.swaggerTypes = {
            'sdid': 'str',
            'field': 'str',
            'startDate': 'long',
            'endDate': 'long',
            'interval': 'str',
            'size': 'long',
            'data': 'list[Aggregates]'

        }


        self.sdid = None # str
        self.field = None # str
        self.startDate = None # long
        self.endDate = None # long
        self.interval = None # str
        self.size = None # long
        self.data = None # list[Aggregates]
        
